### ISSUE TITLE
Typos in NV documentation

### ISSUE THREAD

**Issue by peteingithub** [neuvector/docs#23]
https://open-docs.neuvector.com/basics/overview#scanner
The Scanner is a container which performs the vulnerability and compliance scanning for images, containers and nodes. It is typically deployed as a **replicates** and ... -> replicaset

https://open-docs.neuvector.com/basics/overview#updater
NeuVector **regular** publishes ... -> regularly

https://open-docs.neuvector.com/configuration/users#mapping-groups-to-roles-and-namespaces
Groups can be mapped to preset or **customer** roles in NeuVector. In addition, a role can be restricted to **one or namespaces**. -> custom & one or more

https://open-docs.neuvector.com/navigation/navigation#dashboard
It also details for these security events. -> (something missing?)

https://open-docs.neuvector.com/navigation/navigation#settings-configuration
(References to v4.x. Are these necessary for v5?)

**Comment by gkosaka** [comment]
Thanks, updated! In the future feel free to file PRs.
