### ISSUE TITLE
Please update repos

### ISSUE THREAD

**Issue by kevinayres** [neuvector/docs#47]
Can we correctly mention regustry.suse.com or Amazon ECR? 
https://github.com/neuvector/docs/blob/main/user/pages/01.basics/01.overview/docs.md

**Comment by kevinayres** [comment]
Can we mention that ECS itself is not officially supported? If the AllinOne will not be maiantained going forward then we should mention the end-date. 
https://github.com/neuvector/docs/blob/main/user/pages/02.deploying/08.ecs/docs.md

**Comment by kevinayres** [comment]
We mention Docker hub in the first line "Note: These docs describe the 5.x (Open Source) version. The 5.x images are accessible from Docker Hub " 

Is the chart and bits on registry.suse.com or ECR now and can we update this verbiage? AWS had asked - why do you only mention docker hub?

**Comment by gkosaka** [comment]
Primary location for NeuVector images is on docker hub. Secondary, as part of Rancher SSO install, is mirrored to the rancher registry. The only images on ECR are explicitly for the marketplace based helm install, and tied to specific helm versions supported in the marketplace.
