### ISSUE TITLE
ECS AllinOne package maintenance end-date

### ISSUE THREAD

**Issue by kevinayres** [neuvector/docs#48]
Can we mention that ECS itself is not officially supported? If the 'AllinOne' will not be maintained going forward then we should mention the end-date for maintenance of the package?
https://github.com/neuvector/docs/blob/main/user/pages/02.deploying/08.ecs/docs.md

**Comment by gkosaka** [comment]
NV on ECS is not supported, and it is mentioned in the docs. AllinOne is still supported.

**Comment by kevinayres** [comment]
It's confusing to AWS readers. So the AllinOne package is supported, but NV on ECS is not. I'm not sure they're arriving at the same understanding.
