### ISSUE TITLE
Where can the manager pod run?

### ISSUE THREAD

**Issue by lindhe** [neuvector/docs#63]
What is the recommendation for where the manager pod should be scheduled?

In the [NeuVector Onboarding and Best Practices Guide](https://open-docs.neuvector.com/deploying/production/NV_Onboarding_5.0.pdf), it says:

> Typically, only one is needed and this can run anywhere

In [the documentation](https://open-docs.neuvector.com/deploying/production) it says:

> The manager should be deployed on the node where the controller is running

If the latter is the case, may the manager be scheduled on _any_ node where a controller pod is deployed (in HA mode) or a particular one or all nodes that has controller pods? And should we add `podAffinity` for that condition in the manifests, in that case?

**Comment by gkosaka** [comment]
Manager is stateless and can run anywhere. No need for podAffinity

**Comment by lindhe** [comment]
Great. Then maybe the docs should be updated accordingly? Or have I misunderstood something?
