### ISSUE TITLE
Incorrect indentation

### ISSUE THREAD

**Issue by btat** [neuvector/docs#7]
In step 3 of https://open-docs.neuvector.com/configuration/console/replacecert#generate-and-use-a-pkcs8-self-signed-certificate the indentation inside the code block is rendered incorrectly.

The markdown from the [most recent commit](https://github.com/neuvector/docs/blame/7690a709240b35d4b83058270224b51140c45787/user/pages/03.configuration/01.console/01.replacecert/docs.md#L42-L60) looks correct, but is not reflected on the site.

**Comment by gkosaka** [comment]
Fixing
