### ISSUE TITLE
Typo in troubleshooting docs

### ISSUE THREAD

**Issue by 90er** [neuvector/docs#94]
Hi there,

It seems that there is a typo in the documentation:

I think it should mean "scanner" instead of "controller":

- https://open-docs.neuvector.com/troubleshooting/troubleshooting/#:~:text=For%20performance%20issues%2C%20make%20sure%20the%20controller%20is%20allocated%20enough%20memory%20for%20scanning%20large%20images
- https://github.com/neuvector/docs/blob/main/docs/12.troubleshooting/01.troubleshooting/01.troubleshooting.md?plain=1#L26

**Comment by nunix** [comment]
@90er can I kindly ask you to have a quick look on PR #96 and tell me if this was the place you saw the typo?
Thank you.
